#!/bin/bash

echo "Running PREINST"

DATA_DIR="/var/pybill"
APP_DIR="/opt/psapps/pybill"

make_data_folder() {
    local folder
    for _dir in log bookmark config stock cache
    do
        folder="$DATA_DIR/$_dir"
        [ ! -e "$folder" ] && mkdir -p $folder
        echo $folder
    done

    chown -R www-data:www-data $DATA_DIR
    chmod -R g+w $DATA_DIR
}

server_stop() {
    systemctl stop nginx
    systemctl stop uwsgi-py-bill.service
}

##########
make_data_folder
server_stop
