tables:
  - name: stock_day
    columns:
      - [finance, String16, NotNull, CollateNocase]
      - [stamp, String24, NotNull, CollateNocase, PrimaryKey, Unique]
      - [start, Integer]
      - [end, Integer]
      - [high, Integer]
      - [low, Integer]
      - [volume, Integer]
      - [foreigner, Integer]
      - [frate, Float]
      - [institute, Integer]
      - [person, Integer]
