# -*- coding: utf-8 -*-
# bookmark

bookmark:
    - name: Family
      list:
        - title: Google
          link: http://www.google.com
          icon: true
        - title: Google Trands
          link: http://trends.google.com
          icon: true
        - title: 다음
          link: http://www.daum.net
          icon: true
        - title: 네이버
          link: http://www.naver.com
          icon: true
        - title: 네이버사전
          link: http://endic.naver.com/
          icon: true
        - title: 다음사전
          link: http://alldic.daum.net/index.do?dic=ee
          icon: true
        - title: Speller
          link: http://www.reverso.net/spell-checker/english-spelling-grammar/
        - title: G-Trans
          link: https://translate.google.co.kr/?hl=ko
          icon: true
        - title: N-Trans
          link: http://translate.naver.com/#/ko/en
    - name: Funny
      list:
        - title: Youtube
          link: https://www.youtube.com
        - title: Facebook
          link: https://www.facebook.com
        - title: ZDNet
          link: http://www.zdnet.co.kr
        - title: Clien
          link: https://www.clien.net
        - title: glassdoor
          link: https://www.glassdoor.com

    - name: Cloud Service
      list:
        - title: GMail
          link: https://mail.google.com
          icon: true
        - title: GCalendar
          link: https://calendar.google.com
          icon: false
        - title: GDrive
          link: https://drive.google.com
          icon: true
        - title: GPhoto
          link: https://photos.google.com
          icon: true

