
folder:
    base: /var/pybill
    config:
    user_config: /var/pybill/config/
    bookmark: /var/pybill/bookmark/
    stock: /var/pybill/stock/
    cache: /var/pybill/cache/
    log: /var/pybill/log/

user:
    url: https://example.com

admin:
    email: admin@email.com
